site_name: Tarte - physical audio synthesis
site_author: Thomas Risse
site_description: Physical audio synthesis engine
theme:
  name: material
  palette:
    # Palette for bright mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: red
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top

extra:
  generator: false  # removes the "Made with Material" footer line
extra_css: [extra.css]

markdown_extensions:
- pymdownx.arithmatex:
    generic: true
- footnotes

extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: Made by Thomas Risse using Mkdocs with Material theme

plugins:
  - search
  # - jupyterlite
  - bibtex:
      bib_file: "docs/refs.bib"
  - mkdoxy:
      projects:
        tarte:
          src-dirs: src/ include/ examples/       # path to your C++ sources
          full-doc: true
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h"
            RECURSIVE: YES
            EXCLUDE: "include/external src/deprecated"
            EXCLUDE_PATTERNS: "*/external/* */deprecated/*"

# nav:
#   - Home: index.md
#   - Theory: 
#   - Examples: examples/basic-usage.md
#   - API reference:
#       - Classes: "tarte/annotated.md"
#       - Files: "tarte/files.md"